### ISSUE TITLE
Inserter is borked with Gutenberg plugin enabled

### ISSUE THREAD

**Issue by mikemcalister** [OllieWP/ollie-pro#13]
Why. Just why.

<img width="856" alt="Screenshot 2024-05-21 at 9 23 32 AM" src="https://github.com/OllieWP/ollie-pro/assets/1415737/e580e3f9-254e-4d93-8f70-928f898944f0">

**Comment by patrickposner** [comment]
I'm glad we figured that out now!
I close the issue.
